version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    restart: always

volumes:
  jenkins_home: